<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Alife.Function.DeskPet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sources\Alife\Alife.Framework\Alife.Framework.csproj" />
    <ProjectReference Include="..\..\sources\Alife.Function\Alife.Function.DeskPet\Alife.Function.DeskPet.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
  </ItemGroup>

</Project>
